### ISSUE TITLE
System UI crash on tappinng the data tile

### ISSUE THREAD

**Issue by Afsar-Pasha** [m0m4x/AdvDataPlan#10]
My system UI crashed when I tap the data tile in the qs which shows the data usage.
Android:Lollipop 5.0.1
ROM:Stock Google Android
Advanced Data Plan version:1.0.5 "can't update it says to higher versions"

`java.lang.NoSuchMethodError: com.android.systemui.statusbar.policy.NetworkControllerImpl#getMobileDataNetworkName()#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:443)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:456)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1263)
	at net.m0m4x.android.xposed.advdataplan.HookMain$5.replaceHookedMethod(HookMain.java:571)
	at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
	at com.android.systemui.statusbar.policy.MobileDataControllerImpl.getDataUsageInfo(<Xposed>)
	at com.android.systemui.qs.tiles.CellularTile$CellularDetailAdapter.createDetailView(CellularTile.java)
	at com.android.systemui.qs.QSPanel.handleShowDetailImpl(QSPanel.java)
	at com.android.systemui.qs.QSPanel.handleShowDetailTile(QSPanel.java)
	at com.android.systemui.qs.QSPanel.handleShowDetail(QSPanel.java)
	at com.android.systemui.qs.QSPanel.access$1000(QSPanel.java)
	at com.android.systemui.qs.QSPanel$H.handleMessage(QSPanel.java)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5637)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)`

**Comment by m0m4x** [comment]
Lollipop was not supported. (this module supports only API levels > 22 ).
I've just released a new branch with a few changes for lollipop, so please try this apk.
https://github.com/m0m4x/AdvDataPlan/blob/support-lollipop/apk/AdvDataPlan_debug.apk
Let me know if it works. Bye

**Comment by Afsar-Pasha** [comment]
Didn't worked can't even change the cycle(0 is the default), but now the System UI crash log is slightly different.
![image](https://user-images.githubusercontent.com/25363752/43135183-28a0286a-8f62-11e8-85cc-c4a41cee08e9.png)
`java.lang.NoSuchMethodError: com.android.systemui.statusbar.policy.NetworkControllerImpl#getMobileDataNetworkName()#bestmatch
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:443)
	at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:456)
	at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1263)
	at net.m0m4x.android.xposed.advdataplan.HookMain.getAdvDataUsageInfo(HookMain.java:1209)
	at net.m0m4x.android.xposed.advdataplan.HookMain.-wrap4(HookMain.java)
	at net.m0m4x.android.xposed.advdataplan.HookMain$9.replaceHookedMethod(HookMain.java:599)
	at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:29)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
	at com.android.systemui.statusbar.policy.MobileDataControllerImpl.getDataUsageInfo(<Xposed>)
	at com.android.systemui.qs.tiles.CellularTile$CellularDetailAdapter.createDetailView(CellularTile.java)
	at com.android.systemui.qs.QSPanel.handleShowDetailImpl(QSPanel.java)
	at com.android.systemui.qs.QSPanel.handleShowDetailTile(QSPanel.java)
	at com.android.systemui.qs.QSPanel.handleShowDetail(QSPanel.java)
	at com.android.systemui.qs.QSPanel.access$1000(QSPanel.java)
	at com.android.systemui.qs.QSPanel$H.handleMessage(QSPanel.java)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5637)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)`
Anyways thanks.
