### ISSUE TITLE
Spamming xposed log with error

### ISSUE THREAD

**Issue by timea-techgirl** [m0m4x/AdvDataPlan#8]
This error keeps spamming xposed log. Please fix this. I'm using nexus 5 running marshmallow.

[CODE]
04-28 16:06:34.554 E/Xposed  ( 4625): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.systemui.statusbar.policy.MobileDataControllerImpl
04-28 16:06:34.554 E/Xposed  ( 4625): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at net.m0m4x.android.xposed.advdataplan.HookMain.handleLoadPackage(HookMain.java:446)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at android.os.Looper.loop(Looper.java:148)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at java.lang.reflect.Method.invoke(Native Method)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
04-28 16:06:34.554 E/Xposed  ( 4625): Caused by: java.lang.ClassNotFoundException: com.android.systemui.statusbar.policy.MobileDataControllerImpl
04-28 16:06:34.554 E/Xposed  ( 4625): 	at java.lang.Class.classForName(Native Method)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at java.lang.Class.forName(Class.java:324)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
04-28 16:06:34.554 E/Xposed  ( 4625): 	... 16 more
04-28 16:06:34.554 E/Xposed  ( 4625): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.systemui.statusbar.policy.MobileDataControllerImpl" on path: DexPathList[[zip file "/system/priv-app/Settings/Settings.apk"],nativeLibraryDirectories=[/system/priv-app/Settings/lib/arm, /system/priv-app/Settings/Settings.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
04-28 16:06:34.554 E/Xposed  ( 4625): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-28 16:06:34.554 E/Xposed  ( 4625): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
04-28 16:06:34.554 E/Xposed  ( 4625): 	... 20 more
04-28 16:06:34.554 E/Xposed  ( 4625): 	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.android.systemui.statusbar.policy.MobileDataControllerImpl" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex", dex file "/data/dalvik-cache/xposed_XTypedArraySuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
04-28 16:06:34.554 E/Xposed  ( 4625): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-28 16:06:34.554 E/Xposed  ( 4625): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
04-28 16:06:34.554 E/Xposed  ( 4625): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-28 16:06:34.554 E/Xposed  ( 4625): 		... 21 more
04-28 16:06:34.554 E/Xposed  ( 4625): 		Suppressed: java.lang.ClassNotFoundException: com.android.systemui.statusbar.policy.MobileDataControllerImpl
04-28 16:06:34.554 E/Xposed  ( 4625): 			at java.lang.Class.classForName(Native Method)
04-28 16:06:34.554 E/Xposed  ( 4625): 			at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
04-28 16:06:34.554 E/Xposed  ( 4625): 			at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
04-28 16:06:34.554 E/Xposed  ( 4625): 			at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
04-28 16:06:34.554 E/Xposed  ( 4625): 			... 22 more
04-28 16:06:34.554 E/Xposed  ( 4625): 		Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
[/CODE]

**Comment by m0m4x** [comment]
This will be fixed in the next release. Thank you
